# Generated by Django 2.0.2 on 2018-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_text',
            field=models.TextField(),
        ),
    ]
